<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View More Detail</name>
   <tag></tag>
   <elementGuidId>f51186e9-ed9c-4261-ac1d-7550a964558d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-primary.btn-sm.mt-2.p-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ddbb9a04-8529-475d-8269-e0868dfa2d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.themoviedb.org/movie/565770</value>
      <webElementGuid>3f69608d-b2e8-4ebd-96e2-81b2b812a173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>41956368-39aa-47a7-852b-e6037ff6ecf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>9a85d628-8014-4140-861c-324486a2d04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary btn-sm mt-2 p-2</value>
      <webElementGuid>b996be2c-bc42-4bce-a748-8d70817e01cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View More Detail</value>
      <webElementGuid>b25ea148-4828-4b1f-b1d1-0f6040bfffb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;pb-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;movie-container col-6 col-md-4 col-xl-3 mb-5&quot;]/div[@class=&quot;card movie-card h-100&quot;]/div[@class=&quot;card-body d-flex flex-column justify-content-between&quot;]/a[@class=&quot;btn btn-outline-primary btn-sm mt-2 p-2&quot;]</value>
      <webElementGuid>c9a2e9c2-1aa9-419d-a8e7-49852f731b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>ff881ea8-c3e7-489e-9e5c-6261ef2a0d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View More Detail')]</value>
      <webElementGuid>814b734d-aa1a-4565-b9b4-8080dcabbb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Beetle'])[2]/following::a[1]</value>
      <webElementGuid>b621baa7-66e6-415d-945e-759fc6578471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Science Fiction'])[2]/following::a[1]</value>
      <webElementGuid>13fe4251-251a-4ff0-9c69-32ee8e62767b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meg 2: The Trench'])[1]/preceding::a[1]</value>
      <webElementGuid>a496b303-a3fb-4498-8069-498ef65d5a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[3]/preceding::a[1]</value>
      <webElementGuid>11c51331-63d3-4d09-973e-d52778d3de63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View More Detail']/parent::*</value>
      <webElementGuid>7956fcc7-ed51-49d4-838f-5ce969613a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.themoviedb.org/movie/565770')]</value>
      <webElementGuid>d02ca68b-8ec9-47df-be8c-94366133cae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>92ec2819-858d-4730-9f84-18c42a8c12ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.themoviedb.org/movie/565770' and (text() = 'View More Detail' or . = 'View More Detail')]</value>
      <webElementGuid>5c684f42-56b3-4a50-9b12-c5f1a31dcba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
