<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllActionAdventureAnimationComedyCri_059493</name>
   <tag></tag>
   <elementGuidId>cf8504e4-6cac-4921-ac4b-691a9a48b1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='genre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>196a96f9-49dc-4499-9d29-2f87b21ba86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>ff2cbfba-7b01-4b80-97f7-270d21b4e038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genre</value>
      <webElementGuid>8150fef0-5ec0-417c-a6e3-3546dc85b622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllActionAdventureAnimationComedyCrimeDocumentaryDramaFamilyFantasyHistoryHorrorMusicMysteryRomanceScience FictionTV MovieThrillerWarWestern</value>
      <webElementGuid>c109a05d-2842-421b-a73e-64af7cd7221e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genre&quot;)</value>
      <webElementGuid>e80f4c2c-ad46-447a-95a7-e514e3791bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='genre']</value>
      <webElementGuid>31866c22-1fda-4473-a02e-de42b4ce17b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/nav/div/div/div[2]/div[2]/select</value>
      <webElementGuid>11ba2ca7-c99b-4690-b2f3-ff10c7e20fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genre'])[1]/following::select[1]</value>
      <webElementGuid>de699fb0-7bb8-4f0c-8dd3-6ed898dabd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[2]</value>
      <webElementGuid>09bc58af-955a-457c-abb0-b11931164640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Movie 2023, Genre: All'])[1]/preceding::select[1]</value>
      <webElementGuid>3855782d-c3e0-41de-b969-df60bb828c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::select[1]</value>
      <webElementGuid>9663d4fe-8eb5-44d7-9f76-3f7202bab3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>91a4e6b9-7d8a-46f0-ba83-2bb582bf34d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'genre' and (text() = 'AllActionAdventureAnimationComedyCrimeDocumentaryDramaFamilyFantasyHistoryHorrorMusicMysteryRomanceScience FictionTV MovieThrillerWarWestern' or . = 'AllActionAdventureAnimationComedyCrimeDocumentaryDramaFamilyFantasyHistoryHorrorMusicMysteryRomanceScience FictionTV MovieThrillerWarWestern')]</value>
      <webElementGuid>86647aa4-bc45-472d-9571-0b04c55ed525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
